name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Get package info
        id: packageInfo
        uses: codex-team/action-nodejs-package-info@v1

      - name: Send release data
        uses: codex-team/hawk.releases@v1
        with:
          release: ${{ steps.packageInfo.outputs.name }}-${{ steps.packageInfo.outputs.version }}
          token: ${{ secrets.HAWK_TOKEN }}

      - name: Make envfile with Hawk token
        uses: ozaytsev86/create-env-file@v1
        with:
          file-name: './.env'
          ENV_HAWK_TOKEN: ${{ secrets.HAWK_TOKEN }}

      - name: Build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'electron:prebuild'
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
